name: Laura Maurer
favicon: null
layout_spectrum: 0.51051
typography_spectrum: 0.4955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#90d4d7'
    - '#1f3e81'
    - '#bce4e4'
    - '#b2e0e2'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: follow
    item: null
    url: null
