name: Laura Maurer
favicon: null
layout_spectrum: 0.81982
typography_spectrum: 0.4955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12203d'
    - '#f0ece3'
    - '#d4b5b0'
    - '#7e7f5d'
    - '#791d2c'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: follow
    item: null
    url: null
