name: Laura Maurer
favicon: null
layout_spectrum: 0.51051
typography_spectrum: 0.4955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#adc1c2'
    - '#88a4af'
    - '#19181e'
    - '#a7857b'
    - '#666060'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: follow
    item: null
    url: null
