name: Laura Maurer
favicon: null
layout_spectrum: 0.16576956654898822
typography_spectrum: 0.9341700884979218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131319'
    - '#ffffff'
    - '#82433d'
    - '#c5c6c2'
    - '#ae928a'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
